### ISSUE TITLE
Draw Indexed Vertices

### ISSUE THREAD

**Issue by Maghin** [angeluriot/Dimension3D#2]
Hello,

I like this lib and I've been working on it this weekend.

I use it to display an HeighMap with a VertexBuffer a little bit optimized with indexed vertices.
The change is quite small and is fully retro-compatible (thanks to your lib, I like how it's structured).
Tell me if you want me to try a PR.

I also did cmake config to be able to compile with my own deps without the squeleton project.

> NB: je suis FR mais on parle anglais sur GitHub non ? ^^

**Comment by angeluriot** [comment]
Honnêtement je préfère garder le code le plus simple possible, je ne sais pas à quel point cela va compliquer la création des vertex buffer et si ça nous oblige à les utiliser dans tous les cas, par contre qu'est-ce que tu entends par "cmake config" ?

**Comment by Maghin** [comment]
Salut,

Je vais te proposer la PR dans le we, c'est tout simple et c'est dynamique comme pour les texcoords etc.. Ça respecte le même pattern.

Pour CMAKE c'est juste une configuration indépendante qui permet d'inclure directement la lib ou de l'installer selon les normes standard GNU. Ca fera l'objet d'une autre PR si je te pousse ça, pour le coup ça m'a obliger à réorganiser le dépôt et je comprendrais que tu veuilles le garder tel quel ;)

Bon we
