### ISSUE TITLE
dim::Object copy

### ISSUE THREAD

**Issue by Maghin** [angeluriot/Dimension3D#4]
Il y a un oubli dans la fonction de copie de dim::Object, il y manque la copie du booléen "binded" et du matériau.

J'ajoute la correction à ma PR actuelle.

**Comment by angeluriot** [comment]
J'ai oublié le matériau oui mais par contre il ne faut pas copier binded

**Comment by Maghin** [comment]
Oui effectivement mais il faut le set à false par contre pour éviter un état indéterminé. C'était mon problème, il prennait une valeur int = 220 => true

**Comment by angeluriot** [comment]
Sinon quelque chose que j'ai pas bien compris, on peut toujours créer des objets sans index ?

**Comment by Maghin** [comment]
Oui, l'exemple de test affiche les 3 mesh d'origine + le cube indexé. La fonction draw appelle glDrawArrays ou glDrawElements en fonction de nb_indices

**Comment by angeluriot** [comment]
D'accord
