### ISSUE TITLE
`texture2D` No Such Function

### ISSUE THREAD

**Issue by TheFloatingBrain** [angeluriot/Dimension3D#6]
I got an error running the default shader saying that `texture2D` was not a function in the default shader, changing the one call too `texture2D` to `texuture` seems to fix the problem (Ubuntu 22.04, podman container, GCC-12 + conan & imgui-docking + imgui-sfml 2.5 from [bincrafters community](https://github.com/bincrafters/community/tree/main/recipes/imgui-sfml))

**Comment by angeluriot** [comment]
Fixed
