### ISSUE TITLE
Conan Package 

### ISSUE THREAD

**Issue by TheFloatingBrain** [angeluriot/Dimension3D#7]
I wrote a [conan recipe](https://github.com/TheFloatingBrain/community/tree/main/recipes/dimension3d) for this library and have made a relevant issue for it on [bincrafters community](https://github.com/bincrafters/community/issues/1442) for its inclusion, just thought I would let the contributors know :smile: 

One thing that I did have to do to make it work was edit the recipe for `imgui-sfml` `2.5` to use the `imgui-docking` source in order to make it work, could the dependency on this branch be removed (at least optionally)?

**Comment by angeluriot** [comment]
I don't understand what **connan** and **bincrafters** are.

**Comment by TheFloatingBrain** [comment]
> I don't understand what connan and bincrafters are.

Conan is a package manager to make life easier, instead of installing and linking every library manually conan does it for you, you only need to provide a `conanfile.txt` file that provides some basic info like the library you would like and its version, its like `npm` for node/javascript or `pip` for python except for C++

You can have multiple profiles and versions of the library and it does not get so messy, in your `CMakeLists.txt` you can just specify `${CONAN_LIBS}` to link the libraries, and `include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)` so you dont need to know the paths [here](https://gist.github.com/TheFloatingBrain/80cece426427efed6b1f15ca0807d12c) is an example I made to test the dimension3d package

Bincrafters I guess package a bunch of libraries for conan and host them (or use too), dont know much about it either

**Comment by angeluriot** [comment]
Ok thanks, but I think you're wrong about this library, it's really something I did for me, it's very poorly done, just enough to make my projects work, it doesn't have at all the rigor needed to be part of a package manager.
