### ISSUE TITLE
[question] Small Window

### ISSUE THREAD

**Issue by TheFloatingBrain** [angeluriot/Dimension3D#9]
I have been messing with this library and even when I compile an example, I get this small window 

![Screenshot from 2022-06-09 04-47-08](https://user-images.githubusercontent.com/1550298/172806885-518a4d88-0c2c-4f0b-9a48-d95ba7c65d3a.png)

I have been able to change it a bit by editing Scene.cpp is there a way to make it full screen (and without the boarder)?

**Comment by angeluriot** [comment]
Scenes are made for small windows, if you don't want that, you can forget scenes and use the draw function of the static class `dim::Window`.
